permalink : /:year/:month/:title.html
pygments: true
paginate: 5
lsi: true
exclude: [".git", "update_site"]
url: http://yjyao.com
gems: [ 'jekyll-pandoc-multiple-formats' ]
markdown: redcarpet
name: Yao Yujian
pandoc:
  skip: false
  output: ./tmp
  flags: '--smart'
  site_flags: '--toc'
  outputs:
    markdown:
