permalink : /:year/:month/:title.html
highlighter: pygments
paginate_path: "posts/page:num"
paginate: 7
lsi: false
exclude: [".git", "update_site"]
url: http://yjyao.com
markdown: Pandoc
name: Yao Yujian
pandoc:
  format: html5
  extensions: [smart, mathjax]
