github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
permalink : /:year/:month/:title.html
safe: false
highlighter: rouge
paginate_path: "posts/page:num"
paginate: 7
exclude: [".git", "update_site"]
url: http://yjyao.com
name: Yujian Yao
sass:
    sass_dir: ./style
    style: compressed
